export const GET_USER_DETAILS_EPIC = 'GET_USER_DETAILS_EPIC';
export const GET_USER_DETAILS_SUCCEEDED = 'GET_USER_DETAILS_SUCCEEDED';
export const GET_USER_DETAILS_FAILED = 'GET_USER_DETAILS_FAILED';
export const GET_USER_DETAILS_CANCEL = 'GET_USER_DETAILS_CANCEL';
export const GET_USER_DETAILS_READING = 'GET_USER_DETAILS_READING';
